services:
  - type: web
    name: dorgham-cnc-api
    runtime: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
